apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  VIRTUAL_HOST: c2Ftc3VuZzEway5jb20gd3d3LnNhbXN1bmcxMGsuY29tIHNhbXN1bmcxMGsuY29tLnBlIHd3dy5zYW1zdW5nMTBrLmNvbS5wZQ==
  LETSENCRYPT_HOST: c2Ftc3VuZzEway5jb20gd3d3LnNhbXN1bmcxMGsuY29tIHNhbXN1bmcxMGsuY29tLnBlIHd3dy5zYW1zdW5nMTBrLmNvbS5wZQ==
  LETSENCRYPT_EMAIL: bWFsaWFnYS5wYW50b2phQGdtYWlsLmNvbQ==
  PORT: ODA=
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci5wa2cuZ2l0aHViLmNvbSI6eyJ1c2VybmFtZSI6Im1hbGlhZ2EtcGFudG9qYSIsInBhc3N3b3JkIjoiZ2hwX3dNSENZdG1MVXc2ZHdvQTZWY3NXTUtERDl4WEhGQzNaUUJUdCIsImVtYWlsIjoibWFsaWFnYS5wYW50b2phQGdtYWlsLmNvbSIsImF1dGgiOiJiV0ZzYVdGbllTMXdZVzUwYjJwaE9tZG9jRjkzVFVoRFdYUnRURlYzTm1SM2IwRTJWbU56VjAxTFJFUTVlRmhJUmtNeldsRkNWSFE9In19fQ==
kind: Secret
metadata:
  name: {{ .Release.Name }}-github-registry
type: kubernetes.io/dockerconfigjson
