apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-app-secrets
  labels:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
type: Opaque
data:
  VIRTUAL_HOST: c2Ftc3VuZzEway5jb20gd3d3LnNhbXN1bmcxMGsuY29tIHNhbXN1bmcxMGsuY29tLnBlIHd3dy5zYW1zdW5nMTBrLmNvbS5wZQ==
  LETSENCRYPT_HOST: c2Ftc3VuZzEway5jb20gd3d3LnNhbXN1bmcxMGsuY29tIHNhbXN1bmcxMGsuY29tLnBlIHd3dy5zYW1zdW5nMTBrLmNvbS5wZQ==
  LETSENCRYPT_EMAIL: bWFsaWFnYS5wYW50b2phQGdtYWlsLmNvbQ==
  PORT: ODA=
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOnsidXNlcm5hbWUiOiJnaWFjb21vY3J1eiIsInBhc3N3b3JkIjoiZjNlNTY0M2I5ZDA5Yzk1ZWRiMjRmZjAyMGE4NTc1NjUxODhhNWJmNCIsImVtYWlsIjoiamFudG9uaW9jcnV6QHNhbXN1bmcuY29tLnBlIiwiYXV0aCI6IloybGhZMjl0YjJOeWRYbzZaak5sTlRZME0ySTVaREE1WXprMVpXUmlNalJtWmpBeU1HRTROVGMxTmpVeE9EaGhOV0ptTkE9PSJ9fX0=
kind: Secret
metadata:
  name: {{ .Release.Name }}-github-registry
type: kubernetes.io/dockerconfigjson