apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-issuer
spec:
  acme:
    # Email address used for ACME registration
    email: {{ .Values.email }}
    server: {{ .Values.issuer_server_domain }}
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: {{ .Release.Name }}-private-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx