apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  #type: LoadBalancer
  selector:
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
