
resources:
  limits:
    cpu: '120m'
    memory: '128mi'
  requests:
    cpu: '100m'
    memory: '100mi'
labels:
  name: templates
env:
    - VIRTUAL_HOST
    - LETSENCRYPT_HOST
    - LETSENCRYPT_EMAIL
    - PORT
image: docker.pkg.github.com/giacomo1203/toretto-api/toreto-api:v735216172-dev
domain: 
    - toreto-api.wyracocha.com
replicas: 2
email: 'maliaga.pantoja@gmail.com'
issuer_server_domain: 'https://acme-v02.api.letsencrypt.org/directory'

